name: Boss-Final-Fix
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Clean and Setup Project
        run: |
          # 1. ล้างของเก่าทิ้งให้หมดก่อน
          rm -rf app settings.gradle build.gradle gradlew gradle .gradle
          
          # 2. สร้างโฟลเดอร์ให้ครบ
          mkdir -p app/src/main/java/com/boss/bot
          mkdir -p app/src/main/res/xml
          mkdir -p gradle/wrapper

          # 3. สร้างไฟล์ settings.gradle
          echo "rootProject.name = 'Kokkok-bot'" > settings.gradle
          echo "include ':app'" >> settings.gradle

          # 4. สร้างไฟล์ build.gradle (Project Level)
          # ใช้ Gradle Plugin 8.0.2 ที่เสถียรกับ Gradle 8.0
          printf "buildscript {\n    repositories { google(); mavenCentral() }\n    dependencies { classpath 'com.android.tools.build:gradle:8.0.2'; classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20' }\n}\nallprojects { repositories { google(); mavenCentral() } }" > build.gradle

          # 5. สร้างไฟล์ app/build.gradle (App Level)
          printf "plugins { id 'com.android.application'; id 'kotlin-android' }\nandroid { namespace 'com.boss.bot'; compileSdk 34; defaultConfig { applicationId 'com.boss.bot'; minSdk 24; targetSdk 34; versionCode 1; versionName '1.0' } }\ndependencies { implementation 'androidx.core:core-ktx:1.12.0'; implementation 'androidx.appcompat:appcompat:1.6.1' }" > app/build.gradle

          # 6. สร้างไฟล์ KokKokService.kt (หัวใจบอท)
          printf "package com.boss.bot\nimport android.accessibilityservice.AccessibilityService\nimport android.view.accessibility.AccessibilityEvent\nclass KokKokService : AccessibilityService() {\n    override fun onAccessibilityEvent(event: AccessibilityEvent?) {}\n    override fun onInterrupt() {}\n}" > app/src/main/java/com/boss/bot/KokKokService.kt

          # 7. สร้างไฟล์ AndroidManifest.xml (ใบอนุญาต)
          printf "<?xml version='1.0' encoding='utf-8'?>\n<manifest xmlns:android='http://schemas.android.com/apk/res/android'>\n<application android:label='KokKok Bot'>\n<service android:name='.KokKokService' android:permission='android.permission.BIND_ACCESSIBILITY_SERVICE' android:exported='true'>\n<intent-filter><action android:name='android.view.accessibility.AccessibilityService'/></intent-filter>\n<meta-data android:name='android.accessibilityservice' android:resource='@xml/accessibility_service_config'/></service>\n</application>\n</manifest>" > app/src/main/AndroidManifest.xml
          
          # 8. สร้างไฟล์ Config (ล็อคเป้า Kok Kok)
          printf "<?xml version='1.0' encoding='utf-8'?>\n<accessibility-service xmlns:android='http://schemas.android.com/apk/res/android' android:accessibilityEventTypes='typeWindowStateChanged' android:accessibilityFeedbackType='feedbackGeneric' android:canRetrieveWindowContent='true' android:canPerformGestures='true' android:packageNames='com.kokkok.hero' />" > app/src/main/res/xml/accessibility_service_config.xml

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Force Gradle 8.0
        run: |
          # สร้าง wrapper ด้วยระบบก่อน
          gradle wrapper
          
          # *** ทีเด็ดอยู่ตรงนี้สัส: บังคับแก้ Config ให้ดาวน์โหลด Gradle 8.0 เท่านั้น ***
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          
          chmod +x gradlew

      - name: Build APK (Finally!)
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KokKokBot-Final-Boss
          path: app/build/outputs/apk/debug/*.apk
          
